<a href="https://colab.research.google.com/github/spandangupta/Data602-Data-Analysis-Machine-Learning-Practice/blob/master/Count%2CTD-IDFVectorizerandNaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt-get -qq install -y graphviz && pip install -q pydot
!pip install graphviz
!pip install pydot

In [ ]:
import pandas as pd
from sklearn import datasets
from matplotlib import pyplot
from matplotlib import pyplot
from matplotlib import pylab
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import export_graphviz
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from pydot import graph_from_dot_data

In [ ]:
data_train = datasets.fetch_20newsgroups(subset='train', remove=('headers', 'footers', 'quotes'))
#data_train = datasets.fetch_20newsgroups(subset='train')
data_test = datasets.fetch_20newsgroups(subset='test', remove=('headers', 'footers', 'quotes'))

In [ ]:
data_train.data[:5]

['I was wondering if anyone out there could enlighten me on this car I saw\nthe other day. It was a 2-door sports car, looked to be from the late 60s/\nearly 70s. It was called a Bricklin. The doors were really small. In addition,\nthe front bumper was separate from the rest of the body. This is \nall I know. If anyone can tellme a model name, engine specs, years\nof production, where this car is made, history, or whatever info you\nhave on this funky looking car, please e-mail.',
 "A fair number of brave souls who upgraded their SI clock oscillator have\nshared their experiences for this poll. Please send a brief message detailing\nyour experiences with the procedure. Top speed attained, CPU rated speed,\nadd on cards and adapters, heat sinks, hour of usage per day, floppy disk\nfunctionality with 800 and 1.4 m floppies are especially requested.\n\nI will be summarizing in the next two days, so please add to the network\nknowledge base if you have done the clock upgrade and haven't an

In [ ]:
vectorizer = CountVectorizer()
vectors_train=vectorizer.fit_transform(data_train.data)
vectors_test=vectorizer.transform(data_test.data)

In [ ]:
print(vectorizer.vocabulary_)

{'was': 95844, 'wondering': 97181, 'if': 48754, 'anyone': 18915, 'out': 68847, 'there': 88638, 'could': 30074, 'enlighten': 37335, 'me': 60560, 'on': 68080, 'this': 88767, 'car': 25775, 'saw': 80623, 'the': 88532, 'other': 68781, 'day': 31990, 'it': 51326, 'door': 34809, 'sports': 84538, 'looked': 57390, 'to': 89360, 'be': 21987, 'from': 41715, 'late': 55746, '60s': 9843, 'early': 35974, '70s': 11174, 'called': 25492, 'bricklin': 24160, 'doors': 34810, 'were': 96247, 'really': 76471, 'small': 83426, 'in': 49447, 'addition': 16809, 'front': 41724, 'bumper': 24635, 'separate': 81658, 'rest': 77878, 'of': 67670, 'body': 23480, 'is': 51136, 'all': 17936, 'know': 54632, 'can': 25590, 'tellme': 88143, 'model': 62746, 'name': 64931, 'engine': 37287, 'specs': 84276, 'years': 99911, 'production': 73373, 'where': 96433, 'made': 59079, 'history': 46814, 'or': 68409, 'whatever': 96395, 'info': 49932, 'you': 100208, 'have': 45885, 'funky': 41979, 'looking': 57393, 'please': 71850, 'mail': 59216, 'f

In [ ]:
type(vectors_train)

scipy.sparse.csr.csr_matrix

In [ ]:
type(vectors_test)

scipy.sparse.csr.csr_matrix

In [ ]:
print(vectors_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(vectors_train.shape)
print(vectors_test.shape)

(11314, 101631)
(7532, 101631)


In [ ]:
print(vectors_train)

  (0, 59216)	1
  (0, 71850)	1
  (0, 57393)	1
  (0, 41979)	1
  (0, 45885)	1
  (0, 100208)	1
  (0, 49932)	1
  (0, 96395)	1
  (0, 68409)	1
  (0, 46814)	1
  (0, 59079)	1
  (0, 96433)	1
  (0, 73373)	1
  (0, 99911)	1
  (0, 84276)	1
  (0, 37287)	1
  (0, 64931)	1
  (0, 62746)	1
  (0, 88143)	1
  (0, 25590)	1
  (0, 54632)	1
  (0, 17936)	1
  (0, 51136)	2
  (0, 23480)	1
  (0, 67670)	2
  :	:
  (11313, 81742)	1
  (11313, 81792)	1
  (11313, 40387)	1
  (11313, 47209)	1
  (11313, 25475)	1
  (11313, 90644)	1
  (11313, 6044)	2
  (11313, 44748)	1
  (11313, 22529)	1
  (11313, 68997)	1
  (11313, 46271)	1
  (11313, 2777)	1
  (11313, 66242)	1
  (11313, 20123)	1
  (11313, 57131)	1
  (11313, 64435)	1
  (11313, 18521)	2
  (11313, 41127)	1
  (11313, 66857)	2
  (11313, 68409)	1
  (11313, 37287)	1
  (11313, 41715)	1
  (11313, 51326)	1
  (11313, 68080)	1
  (11313, 60560)	1


In [ ]:
nb = MultinomialNB(alpha=.1)
nb.fit(vectors_train, data_train.target)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [ ]:
print(confusion_matrix(nb.predict(vectors_test), data_test.target))

[[222   1   2   0   0   0   0   0   0   2   1   1   0   3   2  20   1  21
    7  42]
 [  6 324 127  29  45  75  12  12   2   7   2   9  32   7  13   5   1   2
    2   6]
 [  0   0   1   1   1   2   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  2  13 116 284  40   7  26   2   0   0   0   1  22   2   1   2   1   0
    0   0]
 [  0   5  26  16 238   2   7   0   0   0   0   0   4   0   0   1   1   0
    0   0]
 [  3  17  73  14   8 293   5   2   0   8   4   5   6   1   0   0   0   5
    2   2]
 [  1   2   4  12  10   4 311   7   4   3   1   1   4   2   2   0   1   1
    1   1]
 [  2   0   2   6   1   0   7 331  22   2   0   1   7   2   2   1   3   0
    4   3]
 [  5   0   0   0   1   0   2  15 355   1   0   0   4   6   0   1   3   0
    1   3]
 [  0   0   0   0   0   0   0   0   1 332   4   0   0   0   0   0   0   1
    0   0]
 [  1   0   0   0   0   0   2   0   0  12 378   0   0   0   0   0   0   0
    0   1]
 [  2   9   9   2   4   3   0   3   0   1   0 357  28   2   1   2

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
# create the transform
vectorizer11 = TfidfVectorizer()

In [ ]:
vectors_train1=vectorizer11.fit_transform(data_train.data)
vectors_test1=vectorizer11.transform(data_test.data)

In [ ]:
# summarize
print(vectorizer11.vocabulary_)



{'was': 95844, 'wondering': 97181, 'if': 48754, 'anyone': 18915, 'out': 68847, 'there': 88638, 'could': 30074, 'enlighten': 37335, 'me': 60560, 'on': 68080, 'this': 88767, 'car': 25775, 'saw': 80623, 'the': 88532, 'other': 68781, 'day': 31990, 'it': 51326, 'door': 34809, 'sports': 84538, 'looked': 57390, 'to': 89360, 'be': 21987, 'from': 41715, 'late': 55746, '60s': 9843, 'early': 35974, '70s': 11174, 'called': 25492, 'bricklin': 24160, 'doors': 34810, 'were': 96247, 'really': 76471, 'small': 83426, 'in': 49447, 'addition': 16809, 'front': 41724, 'bumper': 24635, 'separate': 81658, 'rest': 77878, 'of': 67670, 'body': 23480, 'is': 51136, 'all': 17936, 'know': 54632, 'can': 25590, 'tellme': 88143, 'model': 62746, 'name': 64931, 'engine': 37287, 'specs': 84276, 'years': 99911, 'production': 73373, 'where': 96433, 'made': 59079, 'history': 46814, 'or': 68409, 'whatever': 96395, 'info': 49932, 'you': 100208, 'have': 45885, 'funky': 41979, 'looking': 57393, 'please': 71850, 'mail': 59216, 'f

In [ ]:
print(vectorizer11.idf_)

[4.83671633 4.76173053 8.25444302 ... 9.64073738 9.64073738 9.64073738]


In [ ]:
# summarize encoded vector
print(vectors_train1.shape)
print(vectors_train1.toarray())

(11314, 101631)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
print(vectors_test1)

In [ ]:
print(vectors_train1)

In [ ]:
nb = MultinomialNB(alpha=.1)
nb.fit(vectors_train1, data_train.target)

MultinomialNB(alpha=0.1, class_prior=None, fit_prior=True)

In [ ]:
print(confusion_matrix(nb.predict(vectors_test), data_test.target))

[[ 63   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   6]
 [  0 295  42  12  13  44   6   4   1   5   0   5  13  11   6   3   0   1
    1   4]
 [  0   4 211  24   9  12   4   0   1   0   0   1   1   0   0   0   0   0
    0   0]
 [  0  13  53 296  46  10  26   2   0   0   0   0  18   3   0   0   1   0
    0   0]
 [  0   7   1  10 251   1   7   0   0   0   0   1   6   0   0   0   0   0
    0   0]
 [  2  17  23   6   0 298   1   0   0   6   3   1   4   1   1   0   0   4
    0   0]
 [  0   2   1   7   6   2 299   7   2   2   0   1   0   0   0   0   1   0
    0   0]
 [  0   0   1   1   1   0   4 321  19   0   0   0   6   1   1   1   0   0
    0   0]
 [  1   0   1   0   0   0   0   2 317   0   0   0   3   0   0   0   0   0
    0   0]
 [  0   0   1   0   0   0   0   0   2 315   3   0   0   0   0   0   0   0
    0   0]
 [  1   1   0   0   0   0   3   2   0  22 380   0   1   0   0   0   0   1
    1   1]
 [  8  23  38  14  25  14   4  14  12   7   1 381  83  10  19   0