<a href="https://colab.research.google.com/github/spandangupta/Data602-Data-Analysis-Machine-Learning-Practice/blob/master/SVM%2C_knn%2C_rndf_on_BostonDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn import datasets
# from matplotlib import pyplot
# from matplotlib import pyplot
# from matplotlib import pylab
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import preprocessing
from sklearn import utils
from sklearn.metrics import confusion_matrix

In [ ]:
data = datasets.load_boston()

In [ ]:
data

{'DESCR': "Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per

In [ ]:
housing_df = pd.DataFrame(data=np.c_[data['data'], data['target']],columns= list(data['feature_names']) + ['target'])

In [ ]:
housing_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [ ]:
x=housing_df[['CRIM',	'ZN',	'INDUS',	'CHAS',	'NOX',	'RM',	'AGE',	'DIS',	'RAD',	'TAX',	'PTRATIO',	'B',	'LSTAT']]
y=housing_df['target']

In [ ]:
x.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [ ]:
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: target, dtype: float64

In [ ]:
x_train_df,  x_test_df,  y_train_df, y_test_df= train_test_split(x, y ,random_state=1)

In [ ]:
# svm with linear KERNEL
linearksvm= svm.SVC(kernel='linear', C=1e3)

In [ ]:
# got an error - check_classification_targets does have continuous - so made the following label encoder change
lab_enc = preprocessing.LabelEncoder()
training_scores_encoded = lab_enc.fit_transform(y_train_df)
print(training_scores_encoded)
print(utils.multiclass.type_of_target(y_train_df))
print(utils.multiclass.type_of_target(y_train_df.astype('int')))
print(utils.multiclass.type_of_target(training_scores_encoded))
# y_train_df=training_scores_encoded

[ 95 118 144  89 118 135  13 125 184  32  27 191  15  95  69  84 123 147
 129 124  80 146  94 177  42  93  52  31 160 143 130 130 136 195 107 138
  39  97  90 118  29  54 134  91 112  43 149  90 121 166  80 202  98 105
 108  63 157  25 102  94 182  85 108 105  38 100  45  22  89 192  76 202
 202  73  70 145  53  63 148 122  93  85  77 113  68 158  71  95 130  64
  31 115  94 101  77  78  71 118 170 126  14  84 173  32  47 134 129  11
 128  74 196 202 133 103   7 106 202 124 168 130  67 154  12  59  35 166
  53   6 140  40  45 146 167  62 152  15  60 163 143 199 143  63 121 164
  35 108  61 134 129 137 101  95  76   1  82  87 110  92  23 125  57  30
 174  16   5 143  73 119  35 183 117 135   3  41  10 114  29  78 135   8
  53 150 118  82 173 132 117  47 142  85 131  92 180  62  50 139 113  50
 150 101 111  33  20  62 165 149 133  79   3  35  28 185 190  74 151  93
  19  65   9  78 119 109 151 178 135 119 189   2  71  82 141  81 156  95
 202  76  95 162  37  69 193  48  74 102  45  96 10

In [ ]:
linearksvm.fit(x_train_df,training_scores_encoded)
# y_test_df=training_scores_encoded1

SVC(C=1000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
# linearksvm.score(x_test_df, y_test_df)
# Classification metrics can't handle a mix of continuous and multiclass targets
# y_test_df=training_scores_encoded1

ValueError: ignored

In [ ]:
lab_enc1 = preprocessing.LabelEncoder()
training_scores_encoded1 = lab_enc.fit_transform(y_test_df)
print(training_scores_encoded)
print(utils.multiclass.type_of_target(y_test_df))
print(utils.multiclass.type_of_target(y_test_df.astype('int')))
print(utils.multiclass.type_of_target(training_scores_encoded1))
# y_test_df=training_scores_encoded1

[ 95 118 144  89 118 135  13 125 184  32  27 191  15  95  69  84 123 147
 129 124  80 146  94 177  42  93  52  31 160 143 130 130 136 195 107 138
  39  97  90 118  29  54 134  91 112  43 149  90 121 166  80 202  98 105
 108  63 157  25 102  94 182  85 108 105  38 100  45  22  89 192  76 202
 202  73  70 145  53  63 148 122  93  85  77 113  68 158  71  95 130  64
  31 115  94 101  77  78  71 118 170 126  14  84 173  32  47 134 129  11
 128  74 196 202 133 103   7 106 202 124 168 130  67 154  12  59  35 166
  53   6 140  40  45 146 167  62 152  15  60 163 143 199 143  63 121 164
  35 108  61 134 129 137 101  95  76   1  82  87 110  92  23 125  57  30
 174  16   5 143  73 119  35 183 117 135   3  41  10 114  29  78 135   8
  53 150 118  82 173 132 117  47 142  85 131  92 180  62  50 139 113  50
 150 101 111  33  20  62 165 149 133  79   3  35  28 185 190  74 151  93
  19  65   9  78 119 109 151 178 135 119 189   2  71  82 141  81 156  95
 202  76  95 162  37  69 193  48  74 102  45  96 10

In [ ]:
linearksvm.score(x_test_df, training_scores_encoded1)

0.007874015748031496

In [ ]:
pred=linearksvm.predict(x_test_df)
pred

array([ 96, 166, 104, 138,  53,  85, 147,  34, 105, 149, 135, 158, 101,
       175, 141,  39,  23, 188, 178,  21,  92,  29, 104,  99, 193,   9,
        30, 101, 186,  31, 107,  78, 200,  29,  97, 106,  39, 176,  14,
        88, 127, 109, 104,  63,  38,   7, 202,  18,  27,  30,  88, 131,
       179,  61,   2, 125,  23, 115,  83, 165,  39, 109,  38,  20, 121,
       185, 202, 101, 130, 117, 148,   1,  39,  71,  83, 101,  91, 133,
       192, 147,  62, 115, 166,  63, 140, 150,  38, 148,  66,  54, 108,
       201,  47,  78,  12, 142,  74, 108, 136, 106,  79,  38, 121, 135,
        35,  97,  33,  48, 185, 115, 174, 155,  20, 146, 201, 158,  84,
        36, 160,  94,  97,  27, 121,  60, 123,  66, 148])

In [ ]:
cm = confusion_matrix(training_scores_encoded1, pred)

In [ ]:
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# svm with rbf KERNEL
rbfsvm= svm.SVC(kernel='rbf', C=1e3, gamma=0.1)

In [ ]:
rbfsvm.fit(x_train_df,training_scores_encoded)

SVC(C=1000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
rbfsvm.score(x_test_df, training_scores_encoded1)

0.0

In [ ]:
rbfpred=rbfsvm.predict(x_test_df)
rbfpred

array([202, 202, 202, 202, 202, 202, 202, 202, 202, 202, 135, 202, 202,
       202, 202, 202, 202, 202, 202, 202,  92, 202, 202, 202, 202, 202,
       202, 202, 186,  31, 202, 202, 200, 202, 202, 202, 202, 202, 202,
       202, 202, 109, 202, 202,  69, 202, 202, 202, 202, 202, 202, 202,
       202, 202, 202, 202, 202, 202, 202, 202, 202, 202,  29, 202, 202,
       202, 202, 202, 202, 202, 202,   1, 202, 202, 202, 202, 202, 202,
       202, 147,  62, 115, 202, 202, 202, 202, 202, 202, 202,  62, 202,
       202, 202, 202, 202, 202, 202, 202, 202, 202, 202,  62, 202, 202,
       202, 202, 202, 202, 202, 202, 202, 202, 202, 202, 202, 202,  84,
       202, 202, 202, 202, 202, 202, 202, 202, 202, 202])

In [ ]:
cmrbf = confusion_matrix(training_scores_encoded1, rbfpred)

In [ ]:
# printing the rbf confusion matrix
cmrbf

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# svm with poly KERNEL
polysvm= svm.SVC(kernel='poly', C=1e3, degree=3)

In [ ]:
polysvm.fit(x_train_df,training_scores_encoded)

SVC(C=1000.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [ ]:
polysvm.score(x_test_df, training_scores_encoded1)

0.007874015748031496

In [ ]:
polypred=polysvm.predict(x_test_df)
polypred

array([146, 158, 102,  98,  53,  73, 147,  34, 105, 102, 135, 154, 101,
       175, 141,  39,  35, 188, 175,  21,  92,  35, 104,  99, 193,   9,
        30, 102, 186,  31, 154,  90, 200,  29,  97, 106,  39,  76,  14,
        88, 127, 109, 104,  63,  24,   7, 202,  38,  83,  29,  88, 150,
        74,  65,   2, 125,  23, 115,  71, 165,  39, 109,  38,  20,  53,
       185, 163, 106, 130,  62, 148,   1,  39,  71,  83, 101,  91, 133,
       192, 147,  81, 115, 166,  20, 140, 150,  39, 148,  66,  69, 108,
       201,  47,  78,  12, 142, 149,  95, 136, 106,  79,  29, 137, 134,
        35,  97,  33,  48, 185,  66, 174, 132,  53, 146, 201, 158,  84,
        36, 160,  94, 127,  27, 137,  60, 123,  66, 148])

In [ ]:
cmpoly = confusion_matrix(training_scores_encoded1, polypred)

In [ ]:
cmpoly

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

# Instantiate learning model (k = 3)
classifier = KNeighborsClassifier(n_neighbors=3)

# Fitting the model
classifier.fit(x_train_df, training_scores_encoded)

# Predicting the Test set results
y_pred = classifier.predict(x_test_df)

In [ ]:
cm = confusion_matrix(training_scores_encoded1, y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
accuracy = accuracy_score(training_scores_encoded1, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 0.79 %.


In [ ]:
# Instantiate learning model (k = 5)
classifier = KNeighborsClassifier(n_neighbors=5)

# Fitting the model
classifier.fit(x_train_df, training_scores_encoded)

# Predicting the Test set results
y_pred = classifier.predict(x_test_df)

In [ ]:
cm = confusion_matrix(training_scores_encoded1, y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
accuracy = accuracy_score(training_scores_encoded1, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 0.79 %.


Random **Forest** 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=123456)
rf.fit(x_train_df, training_scores_encoded)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=123456, verbose=0,
            warm_start=False)

In [ ]:
predicted = rf.predict(x_test_df)
accuracy = accuracy_score(training_scores_encoded1, predicted)
print(f'Out-of-bag score estimate: {rf.oob_score_:.3}')
print(f'Mean accuracy score: {accuracy:.3}')

Out-of-bag score estimate: 0.0369
Mean accuracy score: 0.00787


In [ ]:
cm = confusion_matrix(training_scores_encoded1, predicted)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
help(RandomForestClassifier)