<a href="https://colab.research.google.com/github/spandangupta/Data602-Data-Analysis-Machine-Learning-Practice/blob/master/SVM%2Cknn%2CrndfIris%20Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn import svm

In [ ]:
data = datasets.load_iris()

In [ ]:
data

In [ ]:
iris_df = pd.DataFrame(data=np.c_[data['data'], data['target']],columns= list(data['feature_names']) + ['target'])
iris_df.head()

In [ ]:
x=iris_df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
y=iris_df.target

In [ ]:
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
y.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: target, dtype: float64

In [ ]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [ ]:
x_train_df,  x_test_df,  y_train_df, y_test_df= train_test_split(x, y,random_state=1)

In [ ]:
# svm with linear KERNEL
abc= svm.SVC(kernel='linear', C=1).fit(x_train_df, y_train_df)

In [ ]:
abc.score(x_test_df, y_test_df)

1.0

In [ ]:
compare = np.vstack((y_test_df, pred)).T

In [ ]:
compare

In [ ]:
pred=abc.predict(x_test_df)
pred

array([0., 1., 1., 0., 2., 1., 2., 0., 0., 2., 1., 0., 2., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 0., 2., 1., 0., 0., 1., 2., 1., 2., 1., 2.,
       2., 0., 1., 0.])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test_df, pred)

In [ ]:
#printing the confusion matrix
cm

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

In [ ]:
# svm with polynomial KERNEL
polysvc= svm.SVC(kernel='poly', random_state=0).fit(x_train_df, y_train_df)

In [ ]:
polypred=polysvc.predict(x_test_df)

In [ ]:
polypred

array([0., 1., 1., 0., 2., 1., 2., 0., 0., 2., 1., 0., 2., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 1., 0., 2., 1., 0., 0., 1., 2., 1., 2., 1., 2.,
       2., 0., 1., 0.])

In [ ]:
from sklearn.metrics import confusion_matrix
cmpoly = confusion_matrix(y_test_df, polypred)
cmpoly

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

In [ ]:
#finding accuracy from the confusion matrix.
a = cmpoly.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cmpoly[row,c]
        else:
            falsePred += cmpoly[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelPolyAccuracy = corrPred/(cmpoly.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(cmpoly.sum()))

Correct predictions:  38
False predictions 0
Accuracy of the SVC Clasification is:  1.0


In [ ]:
# svm with rbf KERNEL
rbfsvm= svm.SVC(kernel='rbf', random_state=0).fit(x_train_df, y_train_df)

In [ ]:
# Predicting the Test set results
rbfpred = rbfsvm.predict(x_test_df)

In [ ]:
rbfpred

array([0., 1., 1., 0., 2., 1., 2., 0., 0., 2., 1., 0., 2., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 2., 0., 2., 1., 0., 0., 1., 2., 1., 2., 1., 2.,
       2., 0., 1., 0.])

In [ ]:
# Making the Confusion Matrix
rbfcm = confusion_matrix(y_test_df, rbfpred)
rbfcm



array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])

In [ ]:
#finding accuracy from the confusion matrix.
a = rbfcm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=rbfcm[row,c]
        else:
            falsePred += rbfcm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
kernelRbfAccuracy = corrPred/(rbfcm.sum())
print ('Accuracy of the SVC Clasification is: ', corrPred/(rbfcm.sum()))

Correct predictions:  37
False predictions 1
Accuracy of the SVC Clasification is:  0.9736842105263158


**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

# Instantiate learning model (k = 3)
classifier = KNeighborsClassifier(n_neighbors=3)

# Fitting the model
classifier.fit(x_train_df, y_train_df)

# Predicting the Test set results
y_pred = classifier.predict(x_test_df)

In [ ]:
cm = confusion_matrix(y_test_df, y_pred)
cm

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

In [ ]:
accuracy = accuracy_score(y_test_df, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 100.0 %.


In [ ]:
# Instantiate learning model (k = 5)
classifier = KNeighborsClassifier(n_neighbors=5)

# Fitting the model
classifier.fit(x_train_df, y_train_df)

# Predicting the Test set results
y_pred = classifier.predict(x_test_df)

In [ ]:
cm = confusion_matrix(y_test_df, y_pred)
cm

array([[13,  0,  0],
       [ 0, 16,  0],
       [ 0,  0,  9]])

In [ ]:
accuracy = accuracy_score(y_test_df, y_pred)*100
print('Accuracy of our model is equal ' + str(round(accuracy, 2)) + ' %.')

Accuracy of our model is equal 100.0 %.


Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, oob_score=True, random_state=123456)
rf.fit(x_train_df, y_train_df)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=123456, verbose=0,
            warm_start=False)

In [ ]:
predicted = rf.predict(x_test_df)
accuracy = accuracy_score(y_test_df, predicted)
print(f'Out-of-bag score estimate: {rf.oob_score_:.3}')
print(f'Mean accuracy score: {accuracy:.3}')

Out-of-bag score estimate: 0.964
Mean accuracy score: 0.974


In [ ]:
cm = confusion_matrix(y_test_df, predicted)
cm

array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]])